const correct = {
  "packetId": "249a1289-a299-4f4e-8f02-4fbf6898938d",
  "lenderId": "991bc552-230d-4568-af03-7231c4270f4e",
  "lenderName": "Fastlane Test Bank (Automatic)",
  "vin": "1N4AL3AP8JC231502",
  "claimNumber": "123456",
  "accountNumber": true,
  "ownersName": "Pepe Gomez",
  "ownersStreetAddress": "5 Apple Tree Road",
  "ownersCity": null,
  "ownersZipCode": null,
  "ownersPhoneNumber": "+15555555555",
  "ownersEmailAddress": null,
  "ownersState": null,
  "payoffAmount": null,
  "settlementAmount": "20000.00",
  "amountPaidToLender": null,
  "deductible": "1200.00",
  "dateOfLoss": "2022-09-06T00:00:00.000Z",
  "adjusterName": null,
  "adjusterPhoneNumber": null,
  "adjusterEmailAddress": null,
  "financeType": "Retail",
  "requestingCompanyId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
  "vendorId": "LE",
  "createdAt": "2022-10-11T18:24:14.184Z",
  "updatedAt": "2022-10-11T18:24:34.523Z",
  "make": "NISSAN",
  "model": "Altima",
  "year": "2018",
  "payoutMethodology": null,
  "userId": "79ba8da5-5b51-47c6-a016-5f98c0e22916",
  "archived": false,
  "socialSecurityNumber": null,
  "dateOfBirth": null,
  "titleRemittanceAddress": "04 Oak Street",
  "ownersStreetAddress2": null,
  "titleRemittanceAddressId": null,
  "odometer": "12000",
  "tags": [],
  "vehicleLocation": null,
  "ownersNameUpdated": false,
  "ownersAddressUpdated": false,
  "internalStatusUpdatedAt": "2022-10-11T18:24:34.523Z",
  "internalStatus": "Newly Added to Queue",
  "lenderLogResponseEstimate": null,
  "doNotNotifyUsers": [],
  "ownerRetained": false,
  "causeOfLoss": "Single-Vehicle Collision",
  "titledOwnersName": null,
  "titledOwnersNameVerified": false,
  "reviewAnyChanges": false,
  "receivedByGcm": false,
  "updatedSinceGcm": false,
  "insurerType": "First Party",
  "titledState": null,
  "titledStateVerified": false,
  "titleDocumentAdded": false,
  "statusWhenArchived": null,
  "assignedFaxNumber": "12145010977",
  "unableToVerifyTitledOwner": null,
  "lenderPhoneNumber": null,
  "lenderEmailAddress": null,
  "lenderFaxNumber": "+999-9999-0",
  "lenderHasTitle": false,
  "followupCount": 0,
  "testClaim": false,
  "externalId": null,
  "fullSocialSecurityNumber": null,
  "processingGroup": "lossexpress",
  "outboundQueued": null,
  "name": "Local Admin",
  "interfaceDomain": "http://localhost:3002",
  "documents": [
    {
      "url": "https://fastdata-payoff-received-fax.s3.amazonaws.com/249a1289-a299-4f4e-8f02-4fbf6898938d-Regular PDF.pdf",
      "signedRequest": "https://fastdata-payoff-received-fax.s3.amazonaws.com/249a1289-a299-4f4e-8f02-4fbf6898938d-Regular%20PDF.pdf?AWSAccessKeyId=AKIAROIJ4UWG3OXK4YEZ&Expires=1665513788&Signature=J42RZZIq6nGAh%2BvcOnMl4ApvazU%3D",
      "documentId": "ab770b1d-c52d-4411-8b90-fb6e45b47ddd",
      "documentName": "249a1289-a299-4f4e-8f02-4fbf6898938d-Regular PDF.pdf",
      "createdAt": "2022-10-11T18:24:19.124Z",
      "type": "settlement breakdown"
    },
    {
      "url": "https://fastdata-payoff-received-fax.s3.amazonaws.com/249a1289-a299-4f4e-8f02-4fbf6898938d-Regular PDF.pdf",
      "signedRequest": "https://fastdata-payoff-received-fax.s3.amazonaws.com/249a1289-a299-4f4e-8f02-4fbf6898938d-Regular%20PDF.pdf?AWSAccessKeyId=AKIAROIJ4UWG3OXK4YEZ&Expires=1665513788&Signature=J42RZZIq6nGAh%2BvcOnMl4ApvazU%3D",
      "documentId": "b0e88f4b-62e5-4292-ac44-82bc91108f81",
      "documentName": "249a1289-a299-4f4e-8f02-4fbf6898938d-Regular PDF.pdf",
      "createdAt": "2022-10-11T18:24:22.203Z",
      "type": "valuation report"
    }
  ],
  "payoffQuote": null,
  "letterOfGuaranteeRequest": null,
  "sentFaxes": [],
  "user": {
    "userId": "79ba8da5-5b51-47c6-a016-5f98c0e22916",
    "username": "admin",
    "currentlyActive": true,
    "vendorId": "LE",
    "userRole": "Administrator",
    "emailAddress": "luis.neira2@lossexpress.com",
    "mailingStreetAddress": "1000 Main Street",
    "mailingStreetAddress2": null,
    "mailingCity": "Dallas",
    "mailingZipCode": "75204",
    "mailingState": "TX",
    "name": "Local Admin",
    "mailingAdditionalInfo": "XXX-XXXX",
    "emailNotificationPayoffQuote": true,
    "emailNotificationLoG": true,
    "emailNotificationAlerts": true,
    "zohoDeskContactId": null,
    "reportingInterfaceToken": "tcE9YBcKyw7W2sbjBira4GlebRAX8kq2",
    "emailNotificationDirectMessage": true,
    "phoneNumber": null,
    "requestingCompanyId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
    "disclaimerAcknowledged": "2022-10-10T23:53:07.988Z"
  },
  "lender": {
    "lenderId": "991bc552-230d-4568-af03-7231c4270f4e",
    "lenderName": "Fastlane Test Bank (Automatic)",
    "originatingLenderId": "000FL1",
    "origin": "RO",
    "lenderInformation": {
      "availablePayoffQueries": [
        "vin",
        "accountNumber",
        "socialSecurityNumber"
      ],
      "requiredLetterOfGuaranteeFields": [
        "accountNumber",
        "vin",
        "settlementAmount",
        "dateOfLoss",
        "adjusterName",
        "adjusterPhoneNumber",
        "adjusterEmailAddress",
        "financeType"
      ],
      "requiredPayoffQuoteFields": [
        "accountNumber",
        "vin",
        "ownersName"
      ]
    },
    "createdAt": "2022-10-10T23:53:08.005Z",
    "updatedAt": "2022-10-10T23:53:08.005Z",
    "faxNumber": "+999-9999-0",
    "faxTemplate": "request-form.template",
    "logo": null,
    "logRequestEmailAddress": null,
    "fullyAutomated": false,
    "attn": null,
    "verified": true,
    "streetAddress": null,
    "city": null,
    "state": null,
    "zipCode": null,
    "county": null,
    "fdicId": null,
    "website": null,
    "listedPhoneNumber": null,
    "bankType": null,
    "originType": null,
    "callForPayoffAlways": false,
    "checkPayableTo": null,
    "isSearchable": true,
    "streetAddress2": null,
    "longHoldTime": false,
    "isStackable": true,
    "doNotAutoAssign": false,
    "xPayoffLenderId": null,
    "ssnRequired": false,
    "isCustomerAuthorizationRequired": false,
    "fullSocialSecurityNumberRequired": false,
    "routeOneId": null,
    "dtOriginId": null,
    "averageTurnaroundTime": 3,
    "requiresAccountNumber": false,
    "addresses": [],
    "phoneNumbers": []
  },
  "carrier": {
    "name": "Loss Express",
    "logo": "fastlane-logo-large.png",
    "streetAddress": "1000 Main Street",
    "attnLine": "TEST",
    "city": "Dallas",
    "state": "TX",
    "zipCode": "75204",
    "payoutMethodology": {},
    "emailNotificationPayoffQuote": false,
    "emailNotificationLoG": false,
    "emailPayoffQuoteSubject": "Claim #CLAIM_NUMBER - Payoff Quote Received",
    "emailLoGSubject": "Claim #CLAIM_NUMBER - Letter of Guarantee Received",
    "emailPayoffQuoteGlobalEmailAddress": null,
    "emailLoGGlobalEmailAddress": null,
    "emailAlertSubject": "Claim #CLAIM_NUMBER - Alert Received",
    "routeOneOnly": false,
    "claimNumberValidationRegex": "^[A-Za-z0-9-s_#]+$",
    "claimNumberValidationError": "Claim numbers can only contain the following characters: A-Z, 0-9, -, _, #.",
    "logEnabled": true,
    "ssnAllowed": true,
    "streetAddress2": null,
    "logOnNegativeEquity": true,
    "logOnLease": true,
    "logOnAllRequests": false,
    "autoAddAdjusterInfo": false,
    "autoProcessFailedClaims": false,
    "showAdjusterInfoOnForm": false,
    "requireVehicleLocation": false,
    "onlyStoredRemittanceAddresses": false,
    "enableSettlementBreakdownParsing": false,
    "userRemittanceAddresses": false,
    "combinedDocumentTypes": false,
    "additionalOrderTypes": true,
    "usingExapi": false,
    "testingExapi": false,
    "usersCanEditAnyClaim": false,
    "inactiveOrders": [],
    "canManageOrders": false,
    "canAddNewTitleRemittanceAddress": true,
    "hybridDisplay": false,
    "autoFulfillPayoffOrders": true,
    "requireUploadedDocuments": true,
    "disableNewActivity": false,
    "carrierId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
    "interfaceDomain": "http://localhost:3002"
  },
  "events": [
    {
      "createdAt": "2022-10-11T18:24:14.690Z",
      "eventLogId": "370ebb5d-1184-4ada-8d6b-7d940b2c7cc7",
      "message": "Claim Created",
      "type": "packet-create",
      "user": "Local Admin",
      "worker": null,
      "systemEvent": false,
      "orderId": null
    },
    {
      "createdAt": "2022-10-11T18:24:19.149Z",
      "eventLogId": "eb658640-708c-4039-bee8-7e0b6fde5c5a",
      "message": "Documentation Added (settlement breakdown)",
      "type": "document-added",
      "user": "Local Admin",
      "worker": null,
      "systemEvent": false,
      "orderId": null
    },
    {
      "createdAt": "2022-10-11T18:24:22.215Z",
      "eventLogId": "4b9ac39b-92be-4904-b561-2107d372dba0",
      "message": "Documentation Added (valuation report)",
      "type": "document-added",
      "user": "Local Admin",
      "worker": null,
      "systemEvent": false,
      "orderId": null
    },
    {
      "createdAt": "2022-10-11T18:24:34.519Z",
      "eventLogId": "ff1db0ab-c648-40cf-a1be-0f8691d34433",
      "message": "Order Placed: Payment History",
      "type": "order-placed",
      "user": "Local Admin",
      "worker": null,
      "systemEvent": false,
      "orderId": null
    }
  ],
  "tasks": [
    {
      "taskId": "ef8975ff-9b9a-45c5-9289-4927e8bc6778",
      "packetId": "249a1289-a299-4f4e-8f02-4fbf6898938d",
      "status": "unstarted",
      "scheduledToAppearAt": null,
      "dueBy": "2022-10-11T18:24:34.534Z",
      "priority": 1,
      "assignedTo": null,
      "completionNote": null,
      "createdAt": "2022-10-11T18:24:34.530Z",
      "updatedAt": "2022-10-11T18:24:34.530Z",
      "taskTypeId": "a7bf1174-ef6b-40aa-bf91-4148810efcf0",
      "oldCallId": null,
      "receivedFaxId": null,
      "lenderId": null,
      "processingGroup": "lossexpress",
      "hardcodedId": "FULFILL_ORDER",
      "name": "Fulfill Order(s)",
      "type": {
        "taskTypeId": "a7bf1174-ef6b-40aa-bf91-4148810efcf0",
        "name": "Fulfill Order(s)",
        "icon": "phone",
        "dueBy": "1 hour",
        "createdAt": null,
        "updatedAt": null,
        "hardcodedId": "FULFILL_ORDER",
        "callRequired": false,
        "active": true
      },
      "assignedWorker": null,
      "orders": [
        {
          "taskId": "ef8975ff-9b9a-45c5-9289-4927e8bc6778",
          "orderId": "6d0f7075-0016-4b4b-bdb5-5d1de8c07715",
          "packetId": "249a1289-a299-4f4e-8f02-4fbf6898938d",
          "type": "Payment History",
          "status": "pending",
          "responseDate": null,
          "receivedFaxId": null,
          "createdAt": "2022-10-11T18:24:34.511Z",
          "updatedAt": "2022-10-11T18:24:34.511Z",
          "orderTypeId": "958a6906-6231-420a-8f22-a4d04353f6ab",
          "enabled": true,
          "attemptCount": 0,
          "requestedFromLenderAt": null,
          "spokeWith": null,
          "expectedDeliveryDate": null,
          "fulfilledAt": null,
          "documentId": null,
          "attemptLimit": null,
          "systemAttemptCount": 0,
          "odaFailed": false
        }
      ]
    }
  ],
  "notes": [],
  "callEvents": [],
  "callInProgress": false,
  "orders": [
    {
      "orderId": "6d0f7075-0016-4b4b-bdb5-5d1de8c07715",
      "packetId": "249a1289-a299-4f4e-8f02-4fbf6898938d",
      "type": "Payment History",
      "status": "pending",
      "responseDate": null,
      "receivedFaxId": null,
      "createdAt": "2022-10-11T18:24:34.511Z",
      "updatedAt": "2022-10-11T18:24:34.511Z",
      "orderTypeId": "958a6906-6231-420a-8f22-a4d04353f6ab",
      "enabled": true,
      "attemptCount": 0,
      "requestedFromLenderAt": null,
      "spokeWith": null,
      "expectedDeliveryDate": null,
      "fulfilledAt": null,
      "documentId": null,
      "attemptLimit": null,
      "systemAttemptCount": 0,
      "odaFailed": false,
      "globalAttemptLimit": 2
    }
  ],
  "receivedDocuments": []
}