const wrong = {
  "packetId": "da2ef8a1-ca83-4376-a626-637846c12f64",
  "lenderId": "991bc552-230d-4568-af03-7231c4270f4e",
  "lenderName": "Fastlane Test Bank (Automatic)",
  "vin": "2GTEK19R9W1530701",
  "claimNumber": "72126852",
  "accountNumber": true,
  "ownersName": "Princess Goodwin",
  "ownersStreetAddress": "90 Keith Island",
  "ownersCity": null,
  "ownersZipCode": null,
  "ownersPhoneNumber": "+13139215247",
  "ownersEmailAddress": null,
  "ownersState": null,
  "payoffAmount": null,
  "settlementAmount": "38763.00",
  "amountPaidToLender": null,
  "deductible": "1991.00",
  "dateOfLoss": "2022-09-17T00:00:00.000Z",
  "adjusterName": null,
  "adjusterPhoneNumber": null,
  "adjusterEmailAddress": null,
  "financeType": "Retail",
  "requestingCompanyId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
  "vendorId": "LE",
  "createdAt": "2022-10-11T18:18:23.793Z",
  "updatedAt": "2022-10-11T18:18:23.793Z",
  "make": "CHEVROLET",
  "model": "SILVERADO 1500 LT",
  "year": "2016",
  "payoutMethodology": null,
  "userId": "79ba8da5-5b51-47c6-a016-5f98c0e22916",
  "archived": false,
  "socialSecurityNumber": null,
  "dateOfBirth": null,
  "titleRemittanceAddress": "68 Ullrich Rapid",
  "ownersStreetAddress2": null,
  "titleRemittanceAddressId": null,
  "odometer": "61326",
  "tags": [],
  "vehicleLocation": null,
  "ownersNameUpdated": false,
  "ownersAddressUpdated": false,
  "internalStatusUpdatedAt": "2022-10-11T18:18:23.793Z",
  "internalStatus": "Newly Added to Queue",
  "lenderLogResponseEstimate": null,
  "doNotNotifyUsers": [],
  "ownerRetained": false,
  "causeOfLoss": "Flood",
  "titledOwnersName": null,
  "titledOwnersNameVerified": false,
  "reviewAnyChanges": false,
  "receivedByGcm": false,
  "updatedSinceGcm": false,
  "insurerType": "First Party",
  "titledState": null,
  "titledStateVerified": false,
  "titleDocumentAdded": false,
  "statusWhenArchived": null,
  "assignedFaxNumber": "12145010977",
  "unableToVerifyTitledOwner": null,
  "lenderPhoneNumber": null,
  "lenderEmailAddress": null,
  "lenderFaxNumber": "+999-9999-0",
  "lenderHasTitle": false,
  "followupCount": 0,
  "testClaim": false,
  "externalId": null,
  "fullSocialSecurityNumber": null,
  "processingGroup": "lossexpress",
  "outboundQueued": null,
  "name": "Local Admin",
  "interfaceDomain": "http://localhost:3002",
  "documents": [
    {
      "url": "https://fastdata-payoff-received-fax.s3.amazonaws.com/da2ef8a1-ca83-4376-a626-637846c12f64-Regular PDF.pdf",
      "signedRequest": "https://fastdata-payoff-received-fax.s3.amazonaws.com/da2ef8a1-ca83-4376-a626-637846c12f64-Regular%20PDF.pdf?AWSAccessKeyId=AKIAROIJ4UWG3OXK4YEZ&Expires=1665513905&Signature=XQ2XxS%2FUHHyslz57%2BS5WaMUCTc0%3D",
      "documentId": "8a59d5a0-5aa5-4e77-ae58-61366dacf573",
      "documentName": "da2ef8a1-ca83-4376-a626-637846c12f64-Regular PDF.pdf",
      "createdAt": "2022-10-11T18:18:23.827Z",
      "type": "settlement breakdown"
    },
    {
      "url": "https://fastdata-payoff-received-fax.s3.amazonaws.com/da2ef8a1-ca83-4376-a626-637846c12f64-Regular PDF.pdf",
      "signedRequest": "https://fastdata-payoff-received-fax.s3.amazonaws.com/da2ef8a1-ca83-4376-a626-637846c12f64-Regular%20PDF.pdf?AWSAccessKeyId=AKIAROIJ4UWG3OXK4YEZ&Expires=1665513905&Signature=XQ2XxS%2FUHHyslz57%2BS5WaMUCTc0%3D",
      "documentId": "1b010b6f-a21c-401e-8ce1-d5c1b515ed1f",
      "documentName": "da2ef8a1-ca83-4376-a626-637846c12f64-Regular PDF.pdf",
      "createdAt": "2022-10-11T18:18:23.827Z",
      "type": "valuation report"
    }
  ],
  "payoffQuote": null,
  "letterOfGuaranteeRequest": null,
  "sentFaxes": [],
  "user": {
    "userId": "79ba8da5-5b51-47c6-a016-5f98c0e22916",
    "username": "admin",
    "currentlyActive": true,
    "vendorId": "LE",
    "userRole": "Administrator",
    "emailAddress": "luis.neira2@lossexpress.com",
    "mailingStreetAddress": "1000 Main Street",
    "mailingStreetAddress2": null,
    "mailingCity": "Dallas",
    "mailingZipCode": "75204",
    "mailingState": "TX",
    "name": "Local Admin",
    "mailingAdditionalInfo": "XXX-XXXX",
    "emailNotificationPayoffQuote": true,
    "emailNotificationLoG": true,
    "emailNotificationAlerts": true,
    "zohoDeskContactId": null,
    "reportingInterfaceToken": "tcE9YBcKyw7W2sbjBira4GlebRAX8kq2",
    "emailNotificationDirectMessage": true,
    "phoneNumber": null,
    "requestingCompanyId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
    "disclaimerAcknowledged": "2022-10-10T23:53:07.988Z"
  },
  "lender": {
    "lenderId": "991bc552-230d-4568-af03-7231c4270f4e",
    "lenderName": "Fastlane Test Bank (Automatic)",
    "originatingLenderId": "000FL1",
    "origin": "RO",
    "lenderInformation": {
      "availablePayoffQueries": [
        "vin",
        "accountNumber",
        "socialSecurityNumber"
      ],
      "requiredLetterOfGuaranteeFields": [
        "accountNumber",
        "vin",
        "settlementAmount",
        "dateOfLoss",
        "adjusterName",
        "adjusterPhoneNumber",
        "adjusterEmailAddress",
        "financeType"
      ],
      "requiredPayoffQuoteFields": [
        "accountNumber",
        "vin",
        "ownersName"
      ]
    },
    "createdAt": "2022-10-10T23:53:08.005Z",
    "updatedAt": "2022-10-10T23:53:08.005Z",
    "faxNumber": "+999-9999-0",
    "faxTemplate": "request-form.template",
    "logo": null,
    "logRequestEmailAddress": null,
    "fullyAutomated": false,
    "attn": null,
    "verified": true,
    "streetAddress": null,
    "city": null,
    "state": null,
    "zipCode": null,
    "county": null,
    "fdicId": null,
    "website": null,
    "listedPhoneNumber": null,
    "bankType": null,
    "originType": null,
    "callForPayoffAlways": false,
    "checkPayableTo": null,
    "isSearchable": true,
    "streetAddress2": null,
    "longHoldTime": false,
    "isStackable": true,
    "doNotAutoAssign": false,
    "xPayoffLenderId": null,
    "ssnRequired": false,
    "isCustomerAuthorizationRequired": false,
    "fullSocialSecurityNumberRequired": false,
    "routeOneId": null,
    "dtOriginId": null,
    "averageTurnaroundTime": 3,
    "requiresAccountNumber": false,
    "addresses": [],
    "phoneNumbers": []
  },
  "carrier": {
    "name": "Loss Express",
    "logo": "fastlane-logo-large.png",
    "streetAddress": "1000 Main Street",
    "attnLine": "TEST",
    "city": "Dallas",
    "state": "TX",
    "zipCode": "75204",
    "payoutMethodology": {},
    "emailNotificationPayoffQuote": false,
    "emailNotificationLoG": false,
    "emailPayoffQuoteSubject": "Claim #CLAIM_NUMBER - Payoff Quote Received",
    "emailLoGSubject": "Claim #CLAIM_NUMBER - Letter of Guarantee Received",
    "emailPayoffQuoteGlobalEmailAddress": null,
    "emailLoGGlobalEmailAddress": null,
    "emailAlertSubject": "Claim #CLAIM_NUMBER - Alert Received",
    "routeOneOnly": false,
    "claimNumberValidationRegex": "^[A-Za-z0-9-s_#]+$",
    "claimNumberValidationError": "Claim numbers can only contain the following characters: A-Z, 0-9, -, _, #.",
    "logEnabled": true,
    "ssnAllowed": true,
    "streetAddress2": null,
    "logOnNegativeEquity": true,
    "logOnLease": true,
    "logOnAllRequests": false,
    "autoAddAdjusterInfo": false,
    "autoProcessFailedClaims": false,
    "showAdjusterInfoOnForm": false,
    "requireVehicleLocation": false,
    "onlyStoredRemittanceAddresses": false,
    "enableSettlementBreakdownParsing": false,
    "userRemittanceAddresses": false,
    "combinedDocumentTypes": false,
    "additionalOrderTypes": true,
    "usingExapi": false,
    "testingExapi": false,
    "usersCanEditAnyClaim": false,
    "inactiveOrders": [],
    "canManageOrders": false,
    "canAddNewTitleRemittanceAddress": true,
    "hybridDisplay": false,
    "autoFulfillPayoffOrders": true,
    "requireUploadedDocuments": true,
    "disableNewActivity": false,
    "carrierId": "931cbbba-3ff6-487f-b3b5-76a27c897af2",
    "interfaceDomain": "http://localhost:3002"
  },
  "events": [],
  "tasks": [
    {
      "taskId": "c997ae61-0e97-4d85-a711-24ca95b45fa4",
      "packetId": "da2ef8a1-ca83-4376-a626-637846c12f64",
      "status": "unstarted",
      "scheduledToAppearAt": null,
      "dueBy": "2022-10-11T18:18:23.820Z",
      "priority": 1,
      "assignedTo": null,
      "completionNote": null,
      "createdAt": "2022-10-11T18:18:23.820Z",
      "updatedAt": "2022-10-11T18:18:23.820Z",
      "taskTypeId": "a7bf1174-ef6b-40aa-bf91-4148810efcf0",
      "oldCallId": null,
      "receivedFaxId": null,
      "lenderId": null,
      "processingGroup": "lossexpress",
      "hardcodedId": "FULFILL_ORDER",
      "name": "Fulfill Order(s)",
      "type": {
        "taskTypeId": "a7bf1174-ef6b-40aa-bf91-4148810efcf0",
        "name": "Fulfill Order(s)",
        "icon": "phone",
        "dueBy": "1 hour",
        "createdAt": null,
        "updatedAt": null,
        "hardcodedId": "FULFILL_ORDER",
        "callRequired": false,
        "active": true
      },
      "assignedWorker": null,
      "orders": [
        {
          "taskId": "c997ae61-0e97-4d85-a711-24ca95b45fa4",
          "orderId": "505641b7-3b52-46a4-8ee9-26b443c7215a",
          "packetId": "da2ef8a1-ca83-4376-a626-637846c12f64",
          "type": "Bill of Sale",
          "status": "pending",
          "responseDate": null,
          "receivedFaxId": null,
          "createdAt": "2022-10-11T18:18:23.817Z",
          "updatedAt": "2022-10-11T18:18:23.817Z",
          "orderTypeId": "38615d5d-26e0-406f-833a-ac121210772d",
          "enabled": true,
          "attemptCount": 0,
          "requestedFromLenderAt": null,
          "spokeWith": null,
          "expectedDeliveryDate": null,
          "fulfilledAt": null,
          "documentId": null,
          "attemptLimit": null,
          "systemAttemptCount": 0,
          "odaFailed": false
        }
      ]
    }
  ],
  "notes": [],
  "callEvents": [],
  "callInProgress": false,
  "orders": [
    {
      "orderId": "505641b7-3b52-46a4-8ee9-26b443c7215a",
      "packetId": "da2ef8a1-ca83-4376-a626-637846c12f64",
      "type": "Bill of Sale",
      "status": "pending",
      "responseDate": null,
      "receivedFaxId": null,
      "createdAt": "2022-10-11T18:18:23.817Z",
      "updatedAt": "2022-10-11T18:18:23.817Z",
      "orderTypeId": "38615d5d-26e0-406f-833a-ac121210772d",
      "enabled": true,
      "attemptCount": 0,
      "requestedFromLenderAt": null,
      "spokeWith": null,
      "expectedDeliveryDate": null,
      "fulfilledAt": null,
      "documentId": null,
      "attemptLimit": null,
      "systemAttemptCount": 0,
      "odaFailed": false,
      "globalAttemptLimit": 2
    }
  ],
  "receivedDocuments": []
}