'use strict';

exports.seed = async knex => {
  await knex('order_types').insert([
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '0338fec2-3295-4960-a925-f770a7a418b0',
      'name': 'Contact DMV',
      'dependencies': '["loan payoff request"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '0d6c4a12-80ef-4c6d-a07f-44e1ce71ab1d',
      'name': 'Repo Affidavit',
      'dependencies': '["loan payoff request"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '2c84eaf7-244e-438c-98df-f8b5f1771953',
      'name': 'Title Status',
      'dependencies': '["letter of guarantee"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '38615d5d-26e0-406f-833a-ac121210772d',
      'name': 'Bill of Sale',
      'dependencies': '["loan payoff request"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '4264f370-ed4e-4003-ae9d-f0f00868f5f3',
      'name': 'Letter of Guarantee',
      'dependencies': '[]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '52b04ced-7b8e-4253-a2c7-07b7973deb08',
      'name': 'One and the Same Letter',
      'dependencies': '["loan payoff request"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '6c8a9e6f-6b3f-40ee-bb55-a98f0afb4175',
      'name': 'Lien Release Letter',
      'dependencies': '["letter of guarantee"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '87b2ea57-56a3-42d6-82d3-14277a1d727d',
      'name': 'Copy of Title',
      'dependencies': '[]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '958a6906-6231-420a-8f22-a4d04353f6ab',
      'name': 'Payment History',
      'dependencies': '[]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '9a153f91-729c-4d6d-b577-a6c818959aa4',
      'name': 'Installment Contract',
      'dependencies': '["loan payoff request"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': '9a18d312-e0a9-4417-baca-12e524ee34a3',
      'name': 'Payment Status',
      'dependencies': '["letter of guarantee"]',
    },
    {
      'global_attempt_limit': 2,
      'created_at': null,
      'updated_at': null,
      'order_type_id': 'f7e88ca9-0b37-4ff6-88be-a93651c9ddbe',
      'name': 'Missing Options',
      'dependencies': '["loan payoff request"]',
    },
  ]);
};
